# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ben's Blog
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Ben's blog about life and learning experiences.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://teabens.ml # the base hostname & protocol for your site
github_username:  blueberryapple

# Build settings
future: true

# kramdown
kramdown:
  math_engine: +nil+
